name: Review assign

on:
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  assign:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # ランダムでレビュアーをアサイン
      - uses: hkusu/review-assign-action@v1
        env: 
          REVIEWERS: ${{vars.REVIEWERS}}
        with:
          assignees: ${{ github.actor }}
          reviewers: REVIEWERS
          max-num-of-reviewers: 1
